---
- hosts: all
  become: true
  tasks:
      - name: update apt packages
        apt: 
          upgrade: yes
          update_cache: yes
      - name: Add Docker GPG key
        ansible.builtin.apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
      - name: Add Docker repository
        ansible.builtin.apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
          state: present
      - name: Install packages
        apt:
          pkg:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - docker-compose-plugin
          state: latest
          update_cache: true
      - name: Add user to docker group
        ansible.builtin.command: usermod -aG docker 'lucyadmin'