- hosts: all
  tasks:
    - name: add gpg
      ansible.builtin.command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg
      register: temp_gpg 
    - name: add gpg part 2
      ansible.builtin.command: gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg {{ temp_gpg }}