- hosts: all
  tasks:
    - name: add gpg
      ansible.builtin.command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      register: cmdreturn
    - debug: var=cmdreturn.stdout_lines
    - name: Shell module example
      shell: |
           echo "it works1"
           echo "it works2"
           echo "it works3"