---
- name: Generate an HTML report from jinja template
  hosts: all
  gather_facts: true
  vars:
    local_file: "./report.html" 
    #random settings
    csv_path: /tmp
    csv_filename: report.csv
    headers: Hostname,Distro Ver,Kernel Ver,Last Rebooted
 
  tasks:
  - name: Gather last reboot
    ansible.builtin.shell: last reboot | grep -m1 "" | awk '{ print $1, $6, $7, $8 }'
    register: rebooted
 
  - name: Save CSV headers
    ansible.builtin.lineinfile:
      dest: "{{ csv_path }}/{{ csv_filename }}"
      line: "{{ headers }}"
      create: true
      state: present
    delegate_to: localhost
    run_once: true
 
  - name: Build out CSV file
    ansible.builtin.lineinfile:
      path: "{{ local_file }}"
      dest: "{{ csv_path }}/{{ csv_filename }}"
      line: "{{ inventory_hostname }},{{ ansible_distribution_version }},{{ ansible_kernel }},{{ rebooted.stdout }}"
      create: true
      state: present
    delegate_to: localhost
 
  - name: Read in CSV to variable
    community.general.read_csv:
      path: "{{ csv_path }}/{{ csv_filename }}"
    register: csv_file
    delegate_to: localhost
    run_once: true

  - name: generate template
    template:
       src: report.html.j2
       dest: report.html
    delegate_to: localhost