---
- hosts: all
  become: true
  tasks:
      - name: update apt packages
        apt: 
          upgrade: yes
          update_cache: yes
      - name: Install packages
        apt:
          pkg:
            - qemu-guest-agent
          state: latest
          update_cache: true