---
- name: Playbook - Installing baseline
  hosts: all
  become: true
  tasks:
    - name: "Add docker GPG key"
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: "Add docker repository"
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
    - name: Install docker
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: true
    - name: "Create docker log rotation"
      ansible.builtin.copy:
        dest: "/etc/docker/daemon.json"
        content: |
            {
              "log-driver": "json-file",
              "log-opts": {
              "max-size": "50m",
              "max-file": "3"
              }
            }