---
- hosts: all
  become: true
  tasks:
      - name: Install packages
        ansible.builtin.dnf:
          name:
            - qemu-guest-agent
            - nano
            - net-tools
        state: latest
        update_cache: true



---
- hosts: all
  become: true
  tasks:
      - name: Install packages
        dnf:
          pkg:
            - net-tools
            - qemu-guest-agent
            - nano
          state: latest
          update_cache: true